// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtXBs5PcSAl0ApoJmeolx-mrI3XCgffJo',
    appId: '1:119697802402:web:65778f2cfa528b519803fb',
    messagingSenderId: '119697802402',
    projectId: 'food-app-95d46',
    authDomain: 'food-app-95d46.firebaseapp.com',
    storageBucket: 'food-app-95d46.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjmXKc2knyrJ9wSz0dyQJVAmmU-gIFnSI',
    appId: '1:119697802402:android:3d80c04eb54af1069803fb',
    messagingSenderId: '119697802402',
    projectId: 'food-app-95d46',
    storageBucket: 'food-app-95d46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ-WhgUwWByF4o8oPtQCsAJAu73VvDXpM',
    appId: '1:119697802402:ios:5a93b61d538cb15c9803fb',
    messagingSenderId: '119697802402',
    projectId: 'food-app-95d46',
    storageBucket: 'food-app-95d46.firebasestorage.app',
    iosBundleId: 'com.example.ridersFoodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ-WhgUwWByF4o8oPtQCsAJAu73VvDXpM',
    appId: '1:119697802402:ios:5a93b61d538cb15c9803fb',
    messagingSenderId: '119697802402',
    projectId: 'food-app-95d46',
    storageBucket: 'food-app-95d46.firebasestorage.app',
    iosBundleId: 'com.example.ridersFoodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtXBs5PcSAl0ApoJmeolx-mrI3XCgffJo',
    appId: '1:119697802402:web:4f92422b2121d71f9803fb',
    messagingSenderId: '119697802402',
    projectId: 'food-app-95d46',
    authDomain: 'food-app-95d46.firebaseapp.com',
    storageBucket: 'food-app-95d46.firebasestorage.app',
  );
}
